name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt install libncurses-dev build-essential kernel-package fakeroot gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf -qqy
    - name: make
      run: cp /boot/config-$(uname -r) .config && yes "" | make oldconfig && make -j8
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
