name: Build kernel CI

on:
  push:
    branches: [ master, 'rajneesh/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check cpu cores
      run:  cat /proc/cpuinfo
    - name: pre-install
      run:  sudo apt update && sudo apt install linux-headers-$(uname -r)
    - name: install
      run:  sudo apt install cpio libncurses5-dev build-essential kernel-package fakeroot gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf dwarves -qqy
    - name: make
      run: cp /boot/config-$(uname -r) .config && make olddefconfig && scripts/config --disable SYSTEM_TRUSTED_KEYS && make -j16 && make -j16 modules
    - name: post-build
      run: echo "linux kernel build successful"

